
server.port=8082
logging.config=classpath:logback-localdev.xml
# tomcat
server.tomcat.min-spare-threads=2
server.tomcat.max-threads=10



# actuators
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
management.metrics.enable.http.client.requests=false

serviceuser.username=srvdokdistavstemming
serviceuser.***passord=gammelt_passord***

administrerforsendelse.v1.url=https://app-t8.adeo.no/dokdist/rest/v1/administrerforsendelse