
logging.config=classpath:logback-localdev.xml
# tomcat
server.tomcat.min-spare-threads=2
server.tomcat.max-threads=10

application.name=dokdistavstemming
application.version=@application.version@

# actuators
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
management.metrics.enable.http.client.requests=false


scheduler_interval_cron = 30 21 10 * * 1,2,3,5
scheduler_jira_cron = 30 43 14 * * THU,4