# Spring Boot
logging.config=classpath:logback-nais.xml
spring.jmx.enabled=false
spring.main.banner_mode=off
# tomcat
server.tomcat.min-spare-threads=2
server.tomcat.max-threads=10


application.name=dokdistavstemming
application.version=@application.version@


# actuators
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
management.metrics.enable.http.client.requests=false

administrerforsendelse.v1.url=https://app-t8.adeo.no/dokdist/rest/v1/administrerforsendelse
security-token-service-token.url=https://security-token-service-t4.nais.preprod.local/rest/v1/sts/token
securityTokenService.url=https://sts-t8.test.local/SecurityTokenServiceProvider/

serviceuser.username=srvdokdistavstemming
serviceuser.***passord=gammelt_passord***

server.error.whitelabel.enabled=false