# Spring Boot
logging.config=classpath:logback-nais.xml
spring.jmx.enabled=false
spring.main.banner_mode=off
# tomcat
server.tomcat.min-spare-threads=2
server.tomcat.max-threads=10
server.port=8082


# actuators
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
management.metrics.enable.http.client.requests=false

administrerforsendelse.v1.url=https://dokdist/rest/v1/administrerforsendelse
jira.v1.url=https://jira.adeo.no

scheduler_interval_cron = 0 0 08 * * MON-FRI

server.error.whitelabel.enabled=false