
logging.config=classpath:logback-localdev.xml
# tomcat
server.tomcat.min-spare-threads=2
server.tomcat.max-threads=10

application.name=dokdistavstemming
application.version=@application.version@

# actuators
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
management.metrics.enable.http.client.requests=false

serviceuser.username=srvdokdistavstemming
serviceuser.***passord=gammelt_passord***

jira.username=srvjiradokdistavstemming
jira.***passord=gammelt_passord***

administrerforsendelse.v1.url=https://app-t8.adeo.no/dokdist/rest/v1/administrerforsendelse
security_token_service_token.url=https://security-token-service.nais.preprod.local/rest/v1/sts/token
securityTokenService.url=https://sts-t8.test.local/SecurityTokenServiceProvider/
jira.v1.url=https://jira-q1.adeo.no



scheduler_interval_cron = 0 0 08 * * MON-FRI