kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: dokdistavstemming
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: DOKDISTAVSTEMMING_JIRA_URL
      value: {{ DOKDISTAVSTEMMING_JIRA_URL }}
    - name: DOKDISTAVSTEMMING_ENDPOINTS_DOKARKIV_URL
      value: {{ DOKDISTAVSTEMMING_ENDPOINTS_DOKARKIV_URL }}
    - name: DOKDISTAVSTEMMING_ENDPOINTS_DOKARKIV_SCOPE
      value: {{ DOKDISTAVSTEMMING_ENDPOINTS_DOKARKIV_SCOPE }}
    - name: DOKDISTAVSTEMMING_ENDPOINTS_DOKDISTADMIN_URL
      value: {{ DOKDISTAVSTEMMING_ENDPOINTS_DOKDISTADMIN_URL }}
    - name: DOKDISTAVSTEMMING_ENDPOINTS_DOKDISTADMIN_SCOPE
      value: {{ DOKDISTAVSTEMMING_ENDPOINTS_DOKDISTADMIN_SCOPE }}
    - name: DOKDISTSENTRALPRINT_QDIST009_DIST_S_PRINT_QUEUENAME
      value: {{ DOKDISTSENTRALPRINT_QDIST009_DIST_S_PRINT_QUEUENAME }}
    - name: MQGATEWAY01_CHANNEL_NAME
      value: {{ MQGATEWAY01_CHANNEL_NAME }}
    - name: MQGATEWAY01_CHANNEL_SECURENAME
      value: {{ MQGATEWAY01_CHANNEL_SECURENAME }}
    - name: MQGATEWAY01_CHANNEL_ENABLETLS
      value: "{{ MQGATEWAY01_CHANNEL_ENABLETLS }}"
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  leaderElection: true
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 3072Mi
    requests:
      cpu: 250m
      memory: 2304Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVJIRADOKDISTAVSTEMMING }}
        mountPath: "/var/run/secrets/nais.io/srvjiradokdistavstemming"
      - kvPath: {{ SRVDOKDISTAVSTEMMING }}
        mountPath: "/var/run/secrets/nais.io/srvdokdistavstemming"
  azure:
    application:
      enabled: true
  webproxy: true