kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: dokdistavstemming
  namespace: {{ NAMESPACE }}
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: ADMINISTRERFORSENDELSE_V1_URL
      value: {{ ADMINISTRERFORSENDELSE_V1_URL }}
    - name: JIRA_V1_URL
      value: {{ JIRA_V1_URL }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  leaderElection: true
  liveness:
    path: /internal/isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 1500Mi
    requests:
      cpu: 250m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKDISTAVSTEMMING }}
        mountPath: "/var/run/secrets/nais.io/srvdokdistavstemming"
      - kvPath: {{ SRVJIRADOKDISTAVSTEMMING }}
        mountPath: "/var/run/secrets/nais.io/srvjiradokdistavstemming"
      - kvPath: {{ DOKDISTAVSTEMMING_VAULT }}
        mountPath: "/var/run/secrets/nais.io/vault"
